import styles from './BusiAndPayGetway.module.scss';
import IC from '../../../assets/icons (2)/icons/IC/48.png';
import IOT from '../../../assets/icons (2)/icons/IOT/48px.png';
import staff from '../../../assets/icons (2)/icons/Staff/48px.png'
const BusiAndPayGateway = () => {
    return(
        <>
        <div className={styles.background}>
            <h1 className={styles.intehead}>IoT and Devices Integrations</h1>
            <p className={styles.empowerhead}>In the realm of IoT, we not only connect devices but ensure they collaborate effectively. Our solutions manage vast streams of data,ensuring insights are actionable, processes are optimized, and your IoT ecosystem remains secure.</p>
            <div className={styles.bg}>
                <div className={styles.card}>
                <img src={IOT} className={styles.image}/>
                    <p className={styles.firstside}>Connecting Devices:</p>
                    <p className={styles.secondside}>Ensuring IoT devices communicate effectively with centralized management systems.</p>
                </div>
                <div className={styles.card}>
                <img src={IC} className={styles.image}/>
                    <p className={styles.firstside}>IoT Security Integration:</p>
                    <p className={styles.secondside}>Implementing robust security protocols to safeguard IoT ecosystems from vulnerabilities.</p>
                </div>
                <div className={styles.card}>
                <img src={staff} className={styles.image}/>
                    <p className={styles.firstside}>Data Management:</p>
                    <p className={styles.secondside}>From collection to storage, manage vast amounts of data generated by your IoT devices securely and efficiently.</p>
                </div>

            </div>

        </div>
        </>
    );
}
export default BusiAndPayGateway;